### ISSUE TITLE
DNF (still) gets wrong RPM download size for on-demand repo

### ISSUE THREAD

**Issue by optiz0r** [pulp/pulpcore#2119] opened 2022-01-19 21:53 UTC
Re-opening of https://pulp.plan.io/issues/9213, running the supposedly fixed pulp-rpm versions, dnf still gets the wrong sizes for RPM files downloaded from an on-demand repository. Fetching with curl or wget _sometimes_ causes dnf to then pull the correct content, but not other times. Pulp is in use here via Foreman/Katello nightly (updated regularly).

Issue reliably reproduceable with https://rpm.releases.hashicorp.com/. Every newly released RPM has the same issue.

Installed versions (fix for #9213 supposedly in 3.16.0):
- rubygem-pulp_rpm_client-3.16.1-1.el8.noarch
- python38-pulp-rpm-3.16.1-1.el8.noarch
```
[root@alma-canary ~]# dnf upgrade consul -y
Dependencies resolved.
=================================================================================================================================
 Package                 Architecture            Version                      Repository                                    Size
=================================================================================================================================
Upgrading:
 consul                  x86_64                  1.11.2-1                     sihnon_hashicorp_stable-el8                   37 M

Transaction Summary
=================================================================================================================================
Upgrade  1 Package

Total download size: 37 M
Downloading Packages:
[MIRROR] consul-1.11.2.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 38148438 but expected size is: 38490036
[MIRROR] consul-1.11.2.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 38148438 but expected size is: 38490036
[MIRROR] consul-1.11.2.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 38148438 but expected size is: 38490036
[MIRROR] consul-1.11.2.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 38148438 but expected size is: 38490036
[FAILED] consul-1.11.2.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success                      

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download Packages/c/consul-1.11.2.x86_64.rpm: All mirrors were tried
```

```
[root@alma-canary ~]# wget https://whitefall.jellybean.sihnon.net/pulp/content/sihnon/Library/custom/hashicorp/stable-el8/Packages/c/consul-1.11.2.x86_64.rpm
--2022-01-19 20:41:21--  https://whitefall.jellybean.sihnon.net/pulp/content/sihnon/Library/custom/hashicorp/stable-el8/Packages/c/consul-1.11.2.x86_64.rpm
Connecting to whitefall.jellybean.sihnon.net (whitefall.jellybean.sihnon.net)|81.187.154.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38148438 (36M) [binary/octet-stream]
Saving to: ‘consul-1.11.2.x86_64.rpm.5’

consul-1.11.2.x86_64.rpm.5       100%[=======================================================>]  36.38M  11.5MB/s    in 3.2s    

2022-01-19 20:41:24 (11.5 MB/s) - ‘consul-1.11.2.x86_64.rpm.5’ saved [38148438/38148438]

[root@alma-canary ~]# rpm -K --nosignature consul-1.11.2.x86_64.rpm.5 
consul-1.11.2.x86_64.rpm.5: DIGESTS NOT OK
```

Meanwhile downloading directly from upstream fetches the correct size:

```
[root@alma-canary ~]# dnf install --downloadonly consul-1.11.2 --disablerepo=* --enablerepo=hashicorp
Updating Subscription Management repositories.
Hashicorp Stable - x86_64                                                                        1.0 MB/s | 671 kB     00:00    
Last metadata expiration check: 0:00:01 ago on Wed 19 Jan 2022 21:31:04 UTC.
Dependencies resolved.
=================================================================================================================================
 Package                      Architecture                 Version                         Repository                       Size
=================================================================================================================================
Upgrading:
 consul                       x86_64                       1.11.2-1                        hashicorp                        37 M

Transaction Summary
=================================================================================================================================
Upgrade  1 Package

Total download size: 37 M
DNF will only download packages for the transaction.
Is this ok [y/N]: y
Downloading Packages:
consul-1.11.2.x86_64.rpm                                                                         8.9 MB/s |  37 MB     00:04    
---------------------------------------------------------------------------------------------------------------------------------
Total                                                                                            8.9 MB/s |  37 MB     00:04     
Complete!
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.

[root@alma-canary ~]# ls -l /var/cache/dnf/hashicorp-164999f2fbadbd87/packages/
total 105192
-rw-r--r-- 1 root root 38490036 Jan 19 21:31 consul-1.11.2.x86_64.rpm
```

**Comment by dralley** [comment] 2022-01-24 16:28
Probably the same issue: https://github.com/pulp/pulpcore/issues/2147

**Comment by dralley** [comment] 2022-01-25 16:00
@optiz0r Just to be clear on one detail, it's meant to be fixed in pulpcore 3.16, not pulp_rpm 3.16.  What's your pulpcore version?

**Comment by dralley** [comment] 2022-01-25 16:11
Nonetheless, I've reproduced it.  It does still seem to just be the first download though (the streamed one) - further hits work as expected.


![Screenshot from 2022-01-25 11-02-59](https://user-images.githubusercontent.com/2751996/151014581-b9c822f4-8b12-41fc-987c-2f336d7ee1d0.png)
![Screenshot from 2022-01-25 11-10-31](https://user-images.githubusercontent.com/2751996/151014583-616d1b30-553b-4b17-ae66-16553ff9cad4.png)

**Comment by optiz0r** [comment] 2022-01-25 17:38
Sorry for not specifying the pulp core versions:

```
pulpcore-selinux-1.2.6-2.el8.x86_64
python38-pulpcore-3.16.1-1.el8.noarch
rubygem-pulpcore_client-3.16.0-1.el8.noarch
```

I'm not currently able to reproduce the "first download fails, subsequent downloads succeed" reliably. In fact I have packages that no matter how many times I download them (via dnf, curl, wget), I consistently get the incorrect size.

![image](https://user-images.githubusercontent.com/1030831/151029321-181a5e82-6c2f-4924-8af6-2f27036cfa40.png)
![image](https://user-images.githubusercontent.com/1030831/151029549-aa862c36-b431-471c-b39d-12b620f4c19d.png)

**Comment by dralley** [comment] 2022-01-25 18:39
I still haven't been able to reproduce that - yet.  Maybe there's a bug that was unintentionally fixed on the main branch (which is what I'm using) vs. 3.16.

But we can focus on this first issue and see where we end up after fixing that.

**Comment by dralley** [comment] 2022-01-25 19:57
Brain dump so I don't lose anything:

The size of the "incorrectly" downloaded file is identical to the `Content-Length` of the response from original server / repo.  The difference is that the original response has `Content-Encoding: gzip` set which tells the client "I have applied this encoding, you should reverse it to get the correct data" and the streamed response from Pulp does not.  Thus for the first (streaming) download, depending entirely on the configuration of the remote server / repo, clients of Pulp could end up getting with a gzip-compressed version of the file they were supposed to get because Pulp forgot to tell them to decode the file.

The reason it isn't broken most of the time is that most of the time the remote server / repo doesn't try to gzip-compress RPM files.  It's kind of pointless since they're already internally compressed.

The artifacts that get saved into Pulp's datastore seem to be *correct*, i.e. they are the decompressed versions - on the latest release.  **TODO**: investigate if this was ever not the case in the past and whether that might cause "RPMs always have the wrong sizes"

**Comment by dralley** [comment] 2022-01-25 21:37
If the actual cause is the `Content-Length` header being forwarded when the upstream server uses `Content-Encoding`, then the options are:

* Find a way to turn off `Accept-Encoding` (disadvantage: for *some* files, but probably not RPMs, this might be less efficient)
* Disable `Content-Length` header for all streamed responses (disadvantages: TBD, but `Content-Length` is generally useful)
* Disable `Content-Length` header for all streamed responses IF the remote server used `Content-Encoding` (disadvantages: TBD)

**Comment by mdellweg** [comment] 2022-01-25 21:49
Having dipped a toe into the downloader an streaming logic, i really think forwarding the headers from the upstream server we are downloading in the very same moment is probably a convenient but bad idea. We should really provide the same headers to the client whether we serve streaming or form saved artifacts.

**Comment by dralley** [comment] 2022-01-26 04:30
I strongly agree, although I'd like to hear the motivating reasons - I imagine there are a couple of headers that do need to be passed which is why it was done...  

I think in this case though, setting `Content-Length` deliberately is the mistake, because `aiohttp` would otherwise handle it correctly.  After adding `Content-Length` to the list of headers to exclude everything works great.

![Screenshot from 2022-01-25 23-28-35](https://user-images.githubusercontent.com/2751996/151104104-4f258171-c227-4ea6-86ba-d9fb585b0cb9.png)

**Comment by dralley** [comment] 2022-01-26 04:57
@optiz0r If you're comfortable manually applying and testing a small patch, take a look at the PR and let us know if it fixes the problem completely or if you are still encountering issues.

**Comment by optiz0r** [comment] 2022-01-26 14:50
Patch applied and looking good so far:

wget now gets the correct size download:

```
[root@alma-canary ~]# wget https://whitefall.jellybean.sihnon.net/pulp/content/sihnon/Library/custom/hashicorp/stable-el8/Packages/c/consul-1.11.2.x86_64.rpm
--2022-01-26 14:46:09--  https://whitefall.jellybean.sihnon.net/pulp/content/sihnon/Library/custom/hashicorp/stable-el8/Packages/c/consul-1.11.2.x86_64.rpm
Resolving whitefall.jellybean.sihnon.net (whitefall.jellybean.sihnon.net)... 2001:8b0:3b3:0:250:56ff:fe9a:9f35, 81.187.154.141
Connecting to whitefall.jellybean.sihnon.net (whitefall.jellybean.sihnon.net)|2001:8b0:3b3:0:250:56ff:fe9a:9f35|:443... failed: Permission denied.
Connecting to whitefall.jellybean.sihnon.net (whitefall.jellybean.sihnon.net)|81.187.154.141|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [binary/octet-stream]
Saving to: ‘consul-1.11.2.x86_64.rpm.11’

consul-1.11.2.x86_64.rpm.11                [            <=>                                                           ]  36.71M  15.9MB/s    in 2.3s

2022-01-26 14:46:15 (15.9 MB/s) - ‘consul-1.11.2.x86_64.rpm.11’ saved [38490036]

[root@alma-canary ~]# ls -l consul*
-rw-r--r-- 1 root root 38148438 Jan 14 04:49 consul-1.11.2.x86_64.rpm.10
-rw-r--r-- 1 root root 38490036 Jan 14 04:49 consul-1.11.2.x86_64.rpm.11
```

I was also able to `dnf install boundary` first time (0.7.4 was published 8 days ago, and I'm reasonably sure I haven't tried to download that one in the meantime)

```
[root@alma-canary ~]# dnf install boundary
Updating Subscription Management repositories.
Dependencies resolved.
=========================================================================================================================================================
 Package                         Architecture                  Version                          Repository                                          Size
=========================================================================================================================================================
Installing:
 boundary                        x86_64                        0.7.4-1                          sihnon_hashicorp_stable-el8                         41 M

Transaction Summary
=========================================================================================================================================================
Install  1 Package

Total download size: 41 M
Installed size: 86 M
Is this ok [y/N]: y
Downloading Packages:
boundary-0.7.4-1.x86_64.rpm                                                                                              5.2 MB/s |  41 MB     00:07
---------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                    5.2 MB/s |  41 MB     00:07
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                 1/1
  Installing       : boundary-0.7.4-1.x86_64                                                                                                         1/1
  Verifying        : boundary-0.7.4-1.x86_64                                                                                                         1/1
Installed products updated.

Installed:
  boundary-0.7.4-1.x86_64

Complete!
```

Thank you :)

**Comment by dralley** [comment] 2022-01-26 15:37
@mdellweg We should continue the discussion about how we handle the headers more broadly, if you'd like to file an issue or let it be part of the refactor PR.

**Comment by mdellweg** [comment] 2022-01-26 15:41
Let's discuss in the refactor.

**Closed** 2022-01-26 15:43 UTC
