### ISSUE TITLE
Webserver authentication failure

### ISSUE THREAD

**Issue by bli111** [pulp/pulpcore#2393] opened 2022-03-23 14:16 UTC
**Version**
3.18.1

**Describe the bug**
Webserver authentication on a shared external database received "500 internal Server Error" when post to api.

**To Reproduce**

Add below additional setting to /etc/pulp/settings. Use multiple pulp servers to share the same external postgres db.
REMOTE_USER_ENVIRON_NAME: 'HTTP_REMOTE_USER'
  AUTHENTICATION_BACKENDS: ['pulpcore.app.authentication.PulpNoCreateRemoteUserBackend']
  REST_FRAMEWORK__DEFAULT_AUTHENTICATION_CLASSES:  ['rest_framework.authentication.SessionAuthentication', 'pulpcore.app.authentication.PulpRemoteUserAuthentication']

**Expected behavior**

Expect to receive a valid response.

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by bmbouter** [comment] 2022-03-23 14:28
I'm wondering if this is the same issue as https://github.com/pulp/pulpcore/issues/2260. Basically without a user I believe the Authorization stuff 500 errors.

**Comment by bmbouter** [comment] 2022-03-23 14:37
@bli111 can you post the logged 500 error? Seeing the stacktrace would be helpful.

**Comment by bli111** [comment] 2022-03-24 21:51
There is no log in the /var/log/messages. Only thing I got is 
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 177
Content-Type: text/html
Date: Thu, 24 Mar 2022 21:50:22 GMT
Server: nginx/1.20.1

<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.20.1</center>
</body>
</html>

**Comment by bmbouter** [comment] 2022-03-25 11:05
So the issue is that the way you have that configured won't work. I've tried to improve that documentation [here](). The gist of it is that if you want to use Authorization you need to switch to using the `RemoteUserBackend` instead of `PulpNoCreateRemoteUserBackend`. Or if you want to keep using `PulpNoCreateRemoteUserBackend` you should set `DEFAULT_PERMISSION_CLASSES` also. See these docs [here](https://github.com/pulp/pulpcore/pull/2399/files#diff-a82310fea758407e178b0873029ca96c2d83ad9e73f8fe03bf30f8358de6b008R18).

For this issue I could see a) closing it b) adding a startup logging validation which looks to see if users configured `AUTHENTICATION_BACKENDS` without configuring `DEFAULT_PERMISSION_CLASSES`. I think we should close though because there is another use case where you've already loaded up your DB with users when this configuration makes sense. So I'm going to close.

Please let me know if you think we should do something different with this. Please try the new config and see how it goes.

**Closed by bmbouter** 2022-03-25 11:05 UTC
Labels: Issue, Triage-Needed

**Comment by bmbouter** [comment] 2022-04-02 14:10
@bli111 I want to help you resolve this, but we really need to see the traceback which is in the server-side logs. If you'd like some more interactive help getting those, please join us here and ask https://pulpproject.org/help/#chat-to-us
