### ISSUE TITLE
Incorrect filename

### ISSUE THREAD

**Issue by haiwat** [pulp/pulpcore#3346] opened 2022-10-20 16:03 UTC
**Version**
pulpcore 3.21.1
pulp_rpm 3.18

**Describe the bug**
When I download a repomd.xml from pulp, I get the name as "repodata_repomd.xml". This seems to happen with browsers like Firefox and Chrome but not curl.

Here's part of the 302 url where I can see that filename is set to "repodata_repomd.xml":

```
http://[redacted]/pulp3/artifact/11/5815d8e1db4ac601550a1fd5cdd38fa98719f9c96178fc699eda9b8a209443?response-content-disposition=attachment%3Bfilename%3Drepodata%2Frepomd.xml&response-content-type=text%2Fxml
```

**To Reproduce**
I am just following the guide at https://docs.pulpproject.org/pulp_rpm/workflows/index.html.

**Expected behavior**
I would expect the filename to be "repomd.xml"

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by dralley** [comment] 2022-10-21 14:43
I'm transferring this because it's a snafu with direct artifact serving from pulpcore, the rpm plugin just hits an edge case which I imagine other plugins might not so easily.

**Comment by dralley** [comment] 2022-10-22 21:35
Duplicate of https://github.com/pulp/pulpcore/issues/3342

**Closed by dralley** 2022-10-22 21:35 UTC
Labels: Issue, Triage-Needed
