### ISSUE TITLE
Pulpcore 3.25+ is 2x slower

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulpcore#3970] opened 2023-06-27 14:00 UTC
**Version**
3.25+

**Describe the bug**
API responses are taking twice as long on pulpcore 3.25+

**To Reproduce**
I tested this using the `ghcr.io/pulp/pulp` container image. Ran the following tests on pulpcore 3.23-3.26:

- time curl -u admin:password http://localhost:8090/pulp/api/v3/status/
- time curl -u admin:password http://localhost:8090/pulp/api/v3/repositories/
- time curl -u admin:password http://localhost:8090/pulp/api/v3/distributions/
- time curl -u admin:password http://localhost:8090/pulp/api/v3/access_policies/

Here are the results (times are for the respective API calls listed above)

```
pulp 3.26
.046
.376
.378
.406

pulp 3.25
.057
.421
.408
.387

pulp 3.24
.044
.188
.191
.206

pulp 3.23
.069
.239
.214
.212
```

**Expected behavior**
There shouldn't be such a significant decrease in overall performance for newer versions of pulp.

**Comment by newswangerd** [comment] 2023-06-27 14:05
As @gerrod3 pointed out, the authentication classes seem to be considerably slower. This seems to track with the status endpoint, which is unauthenticated

**Comment by lubosmj** [comment] 2023-06-27 14:17
It would be also worth inspecting all updated third-party libraries in case we rule out that authentication classes are the source of the problem.

**Comment by lubosmj** [comment] 2023-07-19 11:32
I can confirm the performance degradation on a repository synced with 60k packages (fedora https://dl.fedoraproject.org/pub/fedora/linux/releases/38/Everything/x86_64/os/, pulp_rpm):
```
# pulpcore:latest
time http :5001/pulp/api/v3/repositories/rpm/rpm/?with_content=/pulp/api/v3/content/rpm/packages/3cc76384-d78d-4863-9483-870250fa3c47/

0.561s on average
```

```
pulpcore:3.24, backported with_content
time http :5001/pulp/api/v3/repositories/rpm/rpm/?with_content=/pulp/api/v3/content/rpm/packages/3cc76384-d78d-4863-9483-870250fa3c47/

0.403s on average
```

1. First, I ran the queries against 3.24 with oci_env:pulpimage:3.24 and local pulp_rpm 3.20 + pulpcore 3.24.
2. Then, I changed dockerfile to contain oci_env:pulpimage:latest, checked out pulp_rpm and pulpcore to main, built the image, and ran `compose up`.

**Comment by gerrod3** [comment] 2023-07-29 19:26
Here are some of the results of my testing averaging over 100 runs. Each test is ran against a machine with 1 repository and 1000 file content units. My test hits each endpoint one after another all with `?limit=1000`. Another thing to note is that the amount of default access policies increased from 49->61 during pulpcore 3.23. 
| **Mean (us): Endpoint/Version**          | 3.22.7    | 3.23.2    | 3.24.1    | 3.25.1    | 3.28.1    |
| ------------------------------------ | --------- | --------- | --------- | --------- | --------- |
| /pulp/api/v3/status/                 | 9867.05   | 11539.90  | 12247.30  | 13383.33  | 14048.51  |
| /pulp/api/v3/access_policies/        | 129993.03 | 138466.69 | 133423.57 | 285056.05 | 299246.40 |
| /pulp/api/v3/content/file/files/     | 579800.37 | 615334.47 | 716939.12 | 809009.17 | 783134.26 |
| /pulp/api/v3/repositories/file/file/ | 127205.28 | 133159.81 | 132238.86 | 280422.96 | 294310.35 |
| _With No Auth/Perm_                       |           |           |           |           |           |
| /pulp/api/v3/status/                 | 12261.21  | 11262.04  | 12790.87  | 13857.48  | 14274.82  |
| /pulp/api/v3/access_policies/        | 15751.97  | 17732.56  | 18484.35  | 19890.82  | 19489.20  |
| /pulp/api/v3/content/file/files/     | 473025.29 | 512850.74 | 667978.56 | 689378.68 | 633729.56 |
| /pulp/api/v3/repositories/file/file/ | 10779.43  | 13903.19  | 16883.99  | 18644.66  | 15362.75  |

From my results it is evident that the basic authentication class change in 3.25 is the biggest cause of slowdown having double in the amount time taken. However, there does seem to be a slight performance degradation from 3.22 -> 3.24 even without the auth changes, specifically jumping from 3.23 -> 3.24. I'm going to spend some time investigating these versions to see what is going on.

**Comment by gerrod3** [comment] 2023-08-31 00:54
Closing now as we determined the majority of the issue is from the BasicAuth class changes in Django 4.2.

**Closed by gerrod3** 2023-08-31 00:54 UTC
Labels: Performance, Issue
