### ISSUE TITLE
Have the content app redirect requests without a trailing slash

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpcore#3363] opened 2022-10-26 17:38 UTC
If you publish a distribution with a base path of "test" and then go to "/pulp/content/test" you get a 404. The content app should redirect you to "/pulp/content/test/". 

Most web servers redirect users automatically:

```
$ curl https://fixtures.pulpproject.org/file
< HTTP/2 301
< server: nginx/1.14.1
< date: Wed, 26 Oct 2022 20:10:06 GMT
< content-type: text/html
< content-length: 185
< location: /file/
```

**Comment by dkliban** [comment] 2022-12-03 18:56
closing as duplicate of https://github.com/pulp/pulpcore/issues/3173

**Closed by dkliban** 2022-12-03 18:56 UTC
Labels: Feature
