### ISSUE TITLE
Scheduled tasks should stop after N failed attempts

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulpcore#3487] opened 2023-01-07 00:02 UTC
**Version**
pulpcore 3.22

**Describe the bug**
If the migrations fail to properly apply and the hooks for viewsets are not properly registered, the analytics schedule task will fail to dispatch correctly and will spam the logs with 
`pulpcore.tasking.tasks:WARNING: Dispatching scheduled task pulpcore.app.tasks.analytics.post_analytics failed. Creation hook 'add_for_object_creator' was not registered for this view set`

Some logic should be put into place to prevent the task from being reschedule if it fails 3 times or so.

**Comment by ipanova** [comment] 2023-01-10 17:12
3 attempts sounds good to me.

**Comment by gerrod3** [comment] 2023-01-11 14:57
I didn't try to as I instantly destroy the system when I run into this error, but you are probably right that no task would be able to be dispatched.

**Comment by lubosmj** [comment] 2023-01-23 12:30
I had thought about the following variants:
1. Add a new field (e.g., `schedules_count`) to the model `TaskSchedule` which will record the number of retries. After N retries, the task will not be listed in the `dispatch_scheduled_tasks` function that is called after every *beat*. Once a task is successfully dispatched, we can set the field value to 0.
    ```
    TaskSchedule.objects.filter(next_dispatch__lte=now).filter(Q(schedules_count__lt=3) & (Q(last_task=None) | Q(last_task__state__in=TASK_FINAL_STATES)))`
    ```
2. Dynamically change the interval for dispatching yet undispatched tasks. We can agree upon updating the time of the first dispatch exponentially. This also leads us to add a new field to the model (e.g., `dispatching_start_time`). An additional modification will be made to the `dispatch_scheduled_tasks` function too.
    ```
    TaskSchedule.objects.filter(next_dispatch__lte=now).filter(Q(dispatching_start_time__gte=datetime.utcnow()) & (Q(last_task=None) | Q(last_task__state__in=TASK_FINAL_STATES)))`
    ```
3. Do nothing when no scheduled task can be dispatched if the system is in an inconsistent state.

**Comment by mdellweg** [comment] 2023-01-23 13:06
Hah, this raises an interesting question to me. Is this about the scheduled task failing too often so it should not be rescheduled, or about the worker unable to even dispatch the task?
In the latter case, i think the system in question is actually badly broken. How about we do nothing?

**Comment by gerrod3** [comment] 2023-01-23 14:11
Technically in my case when I reported the issue it was about the system being badly broken, but if we are going to allow users to eventually create scheduled tasks we will need to handle the scenario where the task keeps failing (especially if they fail almost instantly), IMO.

**Comment by lubosmj** [comment] 2023-01-23 14:23
Then, another question is: Should we remove TaskSchedule objects in the database once they, .e.g, hit 3 retries?

**Comment by mdellweg** [comment] 2023-01-23 15:09
There are options:
1. Remove (Not nice on users, hard to investigate).
2. Deactivate (Also not nice if users don't check in on scheduled tasks).
3. Backoff (Can lead to starvation if the backing-off interval becomes huge).
4. Continue retrying (Not nice on resources).
5. Any of the above and send a message to the owner (sending mails would be new to Pulp).

The issue really is that I as a user would schedule tasks and want to forget about them, or at least not check in daily. At that point I could just manually run them daily.

**Comment by ipanova** [comment] 2023-01-23 15:27
2. Deactivate 
There always will be available logs with different log messages that are easy to grep and inspect.
Also the failed task report  would contain some information too, and TaskSchedule hasthe fk to the last task.

**Comment by lubosmj** [comment] 2023-01-23 15:31
I am against "sending emails" to the owner. We were trying to do this for some time when we had to deal with spam at pulp.plan.io. We could not use a Gmail account for sending automated messages because the workflow requested an attended login every other time. Other mailing services (SMTP relays) are paid. All this should be done at the owner's level.

Can we all agree upon option 4?

**Comment by gerrod3** [comment] 2023-01-23 15:38
What about a combo of 2 and 4? If a task fails 3 times within its scheduled dispatched window, log a warning to the user and set the task to its next scheduled timeslot. This way resources will hopefully not be strained and if the error was temporary then the task will properly complete the next time.

**Comment by ipanova** [comment] 2023-01-23 22:53
It is generally a good idea to have some fallback scenario when things go south. Whether the scheduled tasks are user schedulable or not it is good to give the flexibility to the persona( user, plugin writer) who creates that schedule. For example, by introducing the `threshold_failure` field one can explicitly set it to the N failures ( 3, 10, 1, etc)  he deems necessary or leave it unset. In that case having some sort of exposed read-only counter like  `consecutive_failures` that will record the failures is also helpful. 
In addition warning logs are always welcome.

**Comment by mdellweg** [comment] 2023-01-24 07:59
> What about a combo of 2 and 4? If a task fails 3 times within its scheduled dispatched window, log a warning to the user and set the task to its next scheduled timeslot. This way resources will hopefully not be strained and if the error was temporary then the task will properly complete the next time.

I'm still unsure about "a task fails". It is only dispatched once in the dispatch window, so it cannot fail three times. If you mean "fails to dispatch" the system is badly broken, and log spamming is a lesser issue for me.

**Comment by lubosmj** [comment] 2023-01-24 10:05
The problem is that we can dispatch a task, but the task will always fail. It will fail here (because the system might be broken): https://github.com/pulp/pulpcore/blob/9e42d069313b7fb1f852ca5ed4d0aca3452cfe7a/pulpcore/tasking/tasks.py#L122-L125. Due to that, the updated `next_dispatch` field will not be saved and the task is going to be dispatched in every single beat anyways. So, maybe, updating the logic with `consecutive_failures` and moving the `save` method above the dispatch call would be fine as well. What do you all think?

**Comment by mdellweg** [comment] 2023-01-24 11:39
I think we are still not consistently talking about the same type of failure. Let me try to describe the two failures with more detail:
1. Dispatch fails. This was demonstrated to happen if the access policy on the task viewset is incompatible with the pulp version. In this case, no task is created in the database and therefore "no task fails". I consider this to be a state of pulp being completely broken. No other task can be dispatched from usual views either. I believe this is not a necessary scenario to fix. This system **should** look completely broken (stack traces and all that jazz).
Sure, we can move the update of `next_dispatch` before the `dispatch` call. But that would at least partly accept that dispatch can fail (not a strong "no" here). Anything that fails before we updated `next_dispatch` will spam the logs.
2. The task is dispatched. But the task when attempting to run enters a failed state. This now is something out of the control of the tasking system. And we can state something like "after a certain amount of failed tries this task should be deactivated/schedule time increased". But before we go that way let's discuss the implication this can have on our analytics task. Failing to properly gather and send analytic data for 3 times in a row means the system will fall off our radar.

**Comment by lubosmj** [comment] 2023-01-24 11:52
Yes, you are right, @mdellweg. I misinterpreted the workflow of the dispatching mechanism. It is correct that it is out of the control of the tasking system once we successfully dispatch a task.

So, in the end, we might seem to conclude that if **tasks cannot be dispatched (as reported in the issue description), the Pulp system is broken and we can do nothing about it**:
- @ipanova 2.) ``probably we should do nothing and keep spamming the logs until an action is taken to fix it.``
- @mdellweg 1.) ``I believe this is not a necessary scenario to fix. This system should look completely broken (stack traces and all that jazz).``

**Comment by ipanova** [comment] 2023-01-24 12:00
ipanova
i think in this particular case we just need to fix the analitycs task so the accesspolicy on the viewset is ok
and for the rest it needs more planning
this is tricky because this is not editable, so once disabled there is no way how to bring it back
x9c4
Well the analytics task is "repaired" by a post-migrate sig. But that is not reliably called fast enough. And if the analytics task fails, we need to fix it. Also it would only fail once a day.
I'm in favor of just closing the issue.
"Have you considered to just do nothing?" Should be part of the triage process. XD
ipanova
if the analytics task execution fails for some reason constantly, this can be reported for investigation and in the meantime the ANALYTICS=False can be set
if the task dispatch failure is fixed in the post-migrate signal, i think it is survivable if it is not 'fast' enough and we'd skip only 1 day report, which is ok i think
( i did not know have the knowledge that this is fixed in the post-migrate signal)
x9c4
That's my point. You don't run migrate daily.
and it's not the dispatch being fixed, but the task schedule being idempotented.
ipanova
in that case i think we can whether close the issue or repurpose  it to address the other aspect of 'disable task if its execution fails

**Comment by mdellweg** [comment] 2023-01-24 12:51
> We can try to add some back-off at least (e.g., 10 re-tries) and then remove all dispatched tasks and report to the logs: "The Pulp system is broken"?

There's no point. Throwing stack traces in the logs is about the best way to tell something is broken but we could not anticipate that failure before, we can get.
Also with the same argument you would need to put handrails around every other line of code in Pulp. And in fact they are there. They are called exceptions.

**Closed** 2023-01-24 12:52 UTC
Labels: Issue, prio-list
